<?php
/**
 * @file
 * Nexteuropa inline page navigation.
 */

define('NEXTEUROPA_INPAGE_NAV_DEPTH', 'h2');

/**
 * Implements hook_init().
 */
function nexteuropa_inpage_nav_init() {
  // Build the anchors.
  _nexteuropa_inpage_nav_markup_anchor();
}

/**
 * Implements hook_block_info().
 */
function nexteuropa_inpage_nav_block_info() {
  $blocks = array();
  $blocks['inline_navigation']['info'] = t('In-page Navigation');
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function nexteuropa_inpage_nav_block_view($delta = '') {
  $block = array();

  // Get our static variable.
  $anchors = &drupal_static('_nexteuropa_inpage_nav_markup_anchor');

  if (is_array($anchors) && $delta === "inline_navigation") {
    // Initialize the block.
    $block['content'] = array();
    $items = array();

    // Also lets try to use the cached node object.
    if (isset($anchors['node'])) {
      $node_title = $anchors['node_title'];
    }
    else {
      $node = menu_get_object();
      $node_title = $node->title;
    }
    // Loop our anchors.
    foreach ($anchors['anchorlist'] as $heading) {
      $items[] = '<a href="#' . $heading['id'] . '" class="inpage_nav__list-item">' . $heading['label'] . '</a>';
    }

    // Include js.
    drupal_add_js(drupal_get_path('module', 'nexteuropa_inpage_nav') . '/js/inpage_nav.js');
    drupal_add_js(array('inpage_navigation' => array('node_title' => $node_title)), 'setting');

    $block['subject'] = t('Page Contents');
    $variables = array(
      'items' => $items,
      'attributes' => array(
        'class' => 'nav inpage-nav__list',
      ),
    );
    $block['content'] = '<div class="inpage-nav is-scrollspy-target">' . theme('item_list', $variables) . '</div>';
  }

  return $block;
}

/**
 * Helper: returns the list of heading anchors in the markup.
 */
function _nexteuropa_inpage_nav_markup_anchor() {
  // Create static.
  $anchors = &drupal_static('_nexteuropa_inpage_nav_markup_anchor');
  // If $anchors is not yet an array we parse it.
  if (!is_array($anchors) && $node = menu_get_object('node')) {
    unset($node->field_core_in_page_navigation);
    $markup = drupal_render(node_view($node));
  }
  else {
    return FALSE;
  }
  // Initialize our array.
  $inpage_nav_list = array();
  // Looking for:
  // H2 elements that have an id attribute or
  // DIV elements with id attributes thats first child is an H2.
  $pattern = "/<" . NEXTEUROPA_INPAGE_NAV_DEPTH . ".*?id=\"(.[^\"]*)\".*?>(.[^\<]*)<\/" . NEXTEUROPA_INPAGE_NAV_DEPTH . ">|<div.[!<]*?id=\"(.[^\"]*)\".*?><" . NEXTEUROPA_INPAGE_NAV_DEPTH . ">(.*?)<\/" . NEXTEUROPA_INPAGE_NAV_DEPTH . ">/i";

  preg_match_all($pattern, $markup, $matches);
  foreach ($matches[1] as $i => $id) {
    $inpage_nav_list[] = array(
      'id' => $matches[1][$i] . $matches[3][$i],
      'label' => strip_tags($matches[2][$i] . $matches[4][$i]),
    );
  }

  // Return the data.
  $anchors = array(
    'anchorlist' => $inpage_nav_list,
    'node_title' => $node->title,
  );
}

/**
 * Implements hook_theme().
 *
 * Used to wrap the items in a specific class BEM way.
 */
function nexteuropa_inpage_nav_theme() {
  return array(
    'inpage_nav_block' => array(
      'template' => "templates/" . 'inpage_nav_block',
      'vars' => NULL,
    ),
  );
}
