<?php
/**
 * @file
 * Settings placeholder.
 */

/**
 * Class to define a style plugin handler.
 */
class views_plugin_style_nexteuropa_context_nav extends views_plugin_style {
  /**
   * Definition.
   */
  public function option_definition() {
    $options = parent::option_definition();
    return $options;
  }

  /**
   * Form.
   */
  public function options_form(&$form, &$form_state) {
    parent::options_form($form, $form_state);

  }
}
