<?php

/**
 * @file
 * nexteuropa_ds_layouts.module
 */

/**
 * Implements hook_ds_layout_info_alter().
 */
function nexteuropa_ds_layouts_ds_layout_info_alter(&$layouts) {
  $path = drupal_get_path('module', 'nexteuropa_ds_layouts');
  // Adding an exaplanatory text for existing templates.
  foreach ($layouts as $template => $values) {
    $layouts[$template]['label'] = t('Unsupported DS template: @existing_label', ['@existing_label' => $layouts[$template]['label']]);
  }

  $existing = $layouts;
  $layouts = [];

  $layouts['ne_entity_three_col'] = [
    'label' => t('NE entity (with page header): 3-col stacked'),
    'path' => $path . '/layouts/ne_entity_three_col',
    'regions' => [
      'left_header' => t('Left Header'),
      'right_header' => t('Right Header'),
      'bottom_header' => t('Bottom Header'),
      'top' => t('Top'),
      'left' => t('Left'),
      'central' => t('Middle'),
      'right' => t('Right'),
    ],
    'form' => TRUE,
    'image' => TRUE,
    'is_nexteuropa' => TRUE,
  ];

  $layouts['ne_entity_three_col_top'] = [
    'label' => t('NE entity (with page header): 3-col stacked top'),
    'path' => $path . '/layouts/ne_entity_three_col_top',
    'regions' => [
      'left_header' => t('Left Header'),
      'right_header' => t('Right Header'),
      'bottom_header' => t('Bottom Header'),
      'top_top' => t('Top'),
      'top_middle_left' => t('Top middle left'),
      'top_middle_right' => t('Top middle right'),
      'top_bottom_left' => t('Top bottom left'),
      'top_bottom_right' => t('Top bottom right'),
      'left' => t('Left'),
      'right' => t('Right'),
      'central' => t('Middle'),
    ],
    'form' => TRUE,
    'image' => TRUE,
    'is_nexteuropa' => TRUE,
  ];

  $layouts['ne_entity_three_col_bottom'] = [
    'label' => t('NE entity (with page header): 3-col stacked bottom'),
    'path' => $path . '/layouts/ne_entity_three_col_bottom',
    'regions' => [
      'left_header' => t('Left Header'),
      'right_header' => t('Right Header'),
      'bottom_header' => t('Bottom Header'),
      'top' => t('Top'),
      'left' => t('Left'),
      'right' => t('Right'),
      'central' => t('Middle'),
      'bottom_left' => t('Bottom Left'),
      'bottom_central' => t('Bottom Middle'),
    ],
    'form' => TRUE,
    'image' => TRUE,
    'is_nexteuropa' => TRUE,
  ];

  $layouts['ne_2col'] = [
    'label' => t('NE Teaser: 2-col'),
    'path' => $path . '/layouts/ne_2col',
    'regions' => [
      'main' => t('Main'),
      'second' => t('Second'),
    ],
    'form' => TRUE,
    'image' => TRUE,
    'is_nexteuropa' => TRUE,
  ];

  $layouts['ne_2col_sidebar_no_link'] = [
    'label' => t('NE Teaser: 2-col - sidebar without link'),
    'path' => $path . '/layouts/ne_2col_sidebar_no_link',
    'regions' => [
      'main' => t('Main'),
      'second' => t('Second'),
    ],
    'form' => TRUE,
    'image' => TRUE,
    'is_nexteuropa' => TRUE,
  ];

  $layouts['ne_1col'] = [
    'label' => t('NE Teaser: 1-col'),
    'path' => $path . '/layouts/ne_1col',
    'regions' => [
      'main' => t('Main'),
    ],
    'form' => TRUE,
    'image' => TRUE,
    'is_nexteuropa' => TRUE,
  ];

  $layouts['ne_1col_section_item'] = [
    'label' => t('NE Teaser: 1-col section item'),
    'path' => $path . '/layouts/ne_1col_section_item',
    'regions' => [
      'title' => t('Title'),
      'description' => t('Description'),
      'children' => t('Children'),
      'links' => t('Links'),
    ],
    'form' => TRUE,
    'image' => TRUE,
    'is_nexteuropa' => TRUE,
  ];

  $layouts['ne_featured_item'] = [
    'label' => t('Component: Featured item'),
    'path' => $path . '/layouts/ne_featured_item',
    'regions' => [
      'featured_image' => t('Featured image'),
      'meta' => t('Meta'),
      'main' => t('Main content'),
    ],
    'form' => TRUE,
    'image' => TRUE,
    'is_nexteuropa' => TRUE,
  ];

  // Putting our templates at the top of the list.
  $layouts = array_merge($layouts, $existing);

  return $layouts;
}
