<?php

/**
 * @file
 * Nexteuropa inline page navigation.
 */

// Constant defining the header format used.
define('NEXTEUROPA_INPAGE_NAV_DEPTH', 'h2');

// Load the helpers.
module_load_include('inc', 'nexteuropa_inpage_nav', 'nexteuropa_inpage_nav.helpers');

/**
 * Implements hook_theme().
 */
function nexteuropa_inpage_nav_theme() {
  return [
    'inpage_nav_block' => [
      'template' => 'inpage_nav_block',
      'path' => drupal_get_path('module', 'nexteuropa_inpage_nav') . '/templates',
      'variables' => [
        'title' => '',
        'links' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_ds_fields_info().
 */
function nexteuropa_inpage_nav_ds_fields_info($entity_type) {
  $fields = [];

  $fields[$entity_type]['in_page_navigation'] = [
    'title' => t('Inpage navigation'),
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    'function' => '_nexteuropa_inpage_nav_render_tmp',
  ];

  return $fields;
}

/**
 * Helper function that acts as a placeholder for the inpage nav.
 *
 * @param array $field
 *   All information on the field and its parent entity.
 *
 * @return string
 *   Space, to have it render.
 */
function _nexteuropa_inpage_nav_render_tmp($field) {
  return ' ';
}

/**
 * Implements hook_entity_view_alter().
 *
 * When we request the inpage navigation, we add a pre render function.
 */
function nexteuropa_inpage_nav_entity_view_alter(&$build, $type) {
  if (isset($build['in_page_navigation'])) {
    $build['#pre_render'][] = '_nexteuropa_inpage_nav_build_inpage_nav';
  }
}
