<?php

/**
 * @file
 * Code for the DT europa settings feature.
 */

include_once 'dt_europa_settings.features.inc';
module_load_include('inc', 'dt_europa_settings', 'dt_europa_settings.helpers');

/**
 * Implements hook_nexteuropa_token_token_handlers().
 */
function dt_europa_settings_nexteuropa_token_token_handlers() {
  return [
    'language_handler' => '\Drupal\dt_europa_settings\LanguageTokenHandler',
  ];
}

/**
 * Implements hook_form_alter().
 */
function dt_europa_settings_form_alter(&$form, &$form_state) {
  if ($form['#form_id'] == 'system_theme_settings') {
    // Build the form.
    $form['europa'] = [
      '#type' => 'fieldset',
      '#title' => t('Europa settings'),
    ];

    $form['europa']['field_introduction'] = [
      '#type' => 'select',
      '#title' => t('Choose a field to be diplayed in the page header for views pages and nodes'),
      '#description' => t('You can choose one of the existing fields with type "long text"'),
      '#options' => _dt_europa_settings_textfields(),
      '#weight' => -1,
      // @codingStandardsIgnoreLine
      '#default_value' => variable_get('ec_europa_introduction_field', FALSE),
    ];

    $form['europa']['site_switcher'] = [
      '#type' => 'radios',
      '#title' => t('Choose which site your website belongs to:'),
      // @codingStandardsIgnoreLine
      '#default_value' => variable_get('ec_europa_site_switcher', 'informational'),
      '#options' => [
        'informational' => t('Informational'),
        'political' => t('Political'),
      ],
      '#weight' => 0,
    ];

    $form['#submit'][] = '_dt_europa_settings_theme_settings_submit';
  }
}

/**
 * Helper function to retrieve the text fields.
 */
function _dt_europa_settings_textfields() {
  $fields = field_read_fields(['type' => 'text_long']);
  $list[] = t('Select an option');

  foreach ($fields as $field_name => $field) {
    if (strpos($field_name, 'field') !== FALSE) {
      $list[$field_name] = $field_name;
    }
  }

  return $list;
}

/**
 * Custom submit function for the theme setting form.
 */
function _dt_europa_settings_theme_settings_submit(&$form, &$form_state) {
  // Save the variable for the intorduction field.
  $field_name = $form_state['values']['field_introduction'];
  if (!empty($field_name)) {
    variable_set('ec_europa_introduction_field', $field_name);
  }

  $switcher = $form_state['values']['site_switcher'];
  variable_set('ec_europa_site_switcher', $switcher);
}

/**
 * Implements hook_translated_menu_link_alter().
 */
function dt_europa_settings_translated_menu_link_alter(&$item, $map) {
  // Make our single links coming from menu items language aware.
  $menus = [
    'menu-nexteuropa-service-links',
    'menu-nexteuropa-inst-links',
    'menu-nexteuropa-site-links',
  ];

  if (in_array($item['menu_name'], $menus)) {
    // @todo Remove this.
    if ($item['title'] != 'Europa Analytics') {
      $item['href'] = token_replace($item['href'] . '_[europa_tokens:europa_interface_language]', $item, []);
    }
  }
}
